#!/bin/bash
# Copy the display.html file from its 'official' location in the parent directory.
# The primes program uses go:embed to load the file contents into a string.
# The file to be embedded must be in the build directory since
# it can't be embedded from another directory or a symbolic link.
cp ../display.html cmd
diff -s ../display.html cmd/display.html
