name: primes
description: Most Inefficient Prime Number Sieve Web Server.
version: 1.0.0
repository: https://github.com/madkins23/prime-sieve

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
